// <auto-generated />
using System;
using FingerprintManagementSystem.ApiAdapter.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FingerprintManagementSystem.ApiAdapter.Migrations
{
    [DbContext(typeof(LocalAppDbContext))]
    [Migration("20260203080423_inital-server")]
    partial class initalserver
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.AllowedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("AllowedUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "",
                            Email = "admin@admin.com",
                            EmployeeId = 7300,
                            FullName = "أحمد زيد الحربي",
                            IsActive = true,
                            IsAdmin = true
                        });
                });

            modelBuilder.Entity("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.Delegation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Delegations");
                });

            modelBuilder.Entity("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.DelegationTerminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DelegationId")
                        .HasColumnType("int");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("WasAssignedBefore")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DelegationId");

                    b.ToTable("DelegationTerminals");
                });

            modelBuilder.Entity("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "المبنى الرئيسي"
                        },
                        new
                        {
                            Id = 2,
                            Name = "المطلاع"
                        },
                        new
                        {
                            Id = 3,
                            Name = "برج التحرير"
                        },
                        new
                        {
                            Id = 4,
                            Name = "صباح السالم"
                        },
                        new
                        {
                            Id = 5,
                            Name = "الجهراء - حكومة مول"
                        },
                        new
                        {
                            Id = 6,
                            Name = "الجهراء - تيماء"
                        },
                        new
                        {
                            Id = 7,
                            Name = "جابر الأحمد"
                        },
                        new
                        {
                            Id = 8,
                            Name = "سعد العبدالله"
                        },
                        new
                        {
                            Id = 9,
                            Name = "الصليبية"
                        },
                        new
                        {
                            Id = 10,
                            Name = "القرين - حكومة مول"
                        },
                        new
                        {
                            Id = 11,
                            Name = "مبارك الكبير"
                        },
                        new
                        {
                            Id = 12,
                            Name = "النهضة"
                        },
                        new
                        {
                            Id = 13,
                            Name = "غرب الجليب"
                        },
                        new
                        {
                            Id = 14,
                            Name = "مواقع أخرى"
                        },
                        new
                        {
                            Id = 15,
                            Name = "السالمي"
                        });
                });

            modelBuilder.Entity("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.TerminalRegionMap", b =>
                {
                    b.Property<string>("TerminalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("TerminalId");

                    b.HasIndex("RegionId");

                    b.ToTable("TerminalRegionMaps");
                });

            modelBuilder.Entity("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.DelegationTerminal", b =>
                {
                    b.HasOne("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.Delegation", "Delegation")
                        .WithMany("Terminals")
                        .HasForeignKey("DelegationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delegation");
                });

            modelBuilder.Entity("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.TerminalRegionMap", b =>
                {
                    b.HasOne("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.Delegation", b =>
                {
                    b.Navigation("Terminals");
                });
#pragma warning restore 612, 618
        }
    }
}
