// <auto-generated />
using FingerprintManagementSystem.ApiAdapter.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FingerprintManagementSystem.ApiAdapter.Migrations
{
    [DbContext(typeof(LocalAppDbContext))]
    [Migration("20260105095050_AddSalmiRegion")]
    partial class AddSalmiRegion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "المبنى الرئيسي"
                        },
                        new
                        {
                            Id = 2,
                            Name = "المطلاع"
                        },
                        new
                        {
                            Id = 3,
                            Name = "برج التحرير"
                        },
                        new
                        {
                            Id = 4,
                            Name = "صباح السالم"
                        },
                        new
                        {
                            Id = 5,
                            Name = "الجهراء - حكومة مول"
                        },
                        new
                        {
                            Id = 6,
                            Name = "الجهراء - تيماء"
                        },
                        new
                        {
                            Id = 7,
                            Name = "جابر الأحمد"
                        },
                        new
                        {
                            Id = 8,
                            Name = "سعد العبدالله"
                        },
                        new
                        {
                            Id = 9,
                            Name = "الصليبية"
                        },
                        new
                        {
                            Id = 10,
                            Name = "القرين - حكومة مول"
                        },
                        new
                        {
                            Id = 11,
                            Name = "مبارك الكبير"
                        },
                        new
                        {
                            Id = 12,
                            Name = "النهضة"
                        },
                        new
                        {
                            Id = 13,
                            Name = "غرب الجليب"
                        },
                        new
                        {
                            Id = 14,
                            Name = "مواقع أخرى"
                        },
                        new
                        {
                            Id = 15,
                            Name = "السالمي"
                        });
                });

            modelBuilder.Entity("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.TerminalRegionMap", b =>
                {
                    b.Property<string>("TerminalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TerminalId");

                    b.HasIndex("RegionId");

                    b.ToTable("TerminalRegionMaps");
                });

            modelBuilder.Entity("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.TerminalRegionMap", b =>
                {
                    b.HasOne("FingerprintManagementSystem.ApiAdapter.Persistence.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
